apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: crewlink
spec:
  template:
    spec:
      containers:
        - name: redis
          args:
            - redis-server
            - --maxmemory
            - 32mb
            - --maxmemory-policy
            - allkeys-lru
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
